config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  resources :housings do
    resources :reviews, only: %i[create]
    resources :books, only: %i[create]
  end

  get '/books', to: 'books#index'

  #shallow
  devise_for :users
  root to: "pages#home"
  # get '/home', to: 'pages#home'
  # post '/offers', to: 'offers#index'
  # post '/products', to: 'products#create'
  # put '/products/:id', to: 'products#update'
  # delete '/products/:id', to: 'products#destroy'
  # post '/bookings', to: 'bookings#create'
  # post '/reviews', to: 'reviews#create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'pages/example', to: 'pages#example'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  belongs_to :housing
end

app/models/housing.rb
class Housing < ApplicationRecord
  belongs_to :user
  has_many :reviews



  def averagee_rating
    self.reviews.average(:rating).to_f.truncate(1)  
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :housing
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :housings
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.all
  end

  def show
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(booking_params)
    if @book.save
      redirect_to booking_path(@book), notice: 'book was successfully created.'
    else
      render :new #agregar unprocesable entitity
    end
  end

  def edit
  end

  def update
    if @book.update(booking_params)
      redirect_to booking_path(@book), notice: 'book was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to bookings_path, notice: 'book was successfully destroyed.'
  end

    private

    def set_booking
      @book = book.find(params[:id])
    end

    def booking_params
      params.require(:book).permit(:user_id, :housing_id, :start_date, :end_date, :guests)
    end
end

app/controllers/housings_controller.rb
class HousingsController < ApplicationController
  skip_before_action :authenticate_user!, only: :show
  before_action :set_housing, only: %i[ show edit update destroy ]

  # GET /housings or /housings.json
  def index
    @housings = Housing.where(user_id:current_user.id)
  end

  # GET /housings/1 or /housings/1.json
  def show
    @review = Review.new
    @book = Book.new
  end

  # GET /housings/new
  def new
    @housing = Housing.new
  end

  # GET /housings/1/edit
  def edit
  end

  # POST /housings or /housings.json
  def create
    @housing = Housing.new(housing_params)
    @user_id =  current_user.id
    @housing.user_id = @user_id
    respond_to do |format|
      if @housing.save
        format.html { redirect_to housing_url(@housing), notice: "Housing was successfully created." }
        format.json { render :show, status: :created, location: @housing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @housing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /housings/1 or /housings/1.json
  def update
    respond_to do |format|
      if @housing.update(housing_params)
        format.html { redirect_to housing_url(@housing), notice: "Housing was successfully updated." }
        format.json { render :show, status: :ok, location: @housing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @housing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /housings/1 or /housings/1.json
  def destroy
    @housing.destroy

    respond_to do |format|
      format.html { redirect_to housings_url, notice: "Housing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_housing
      @housing = Housing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def housing_params
      params.require(:housing).permit(:name, :user_id, :price, :amount_bathrooms, :amount_rooms, :msquare, :city, :state, :address)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @housings = Housing.all
  end

  def example
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @housing =  Housing.find(params[:housing_id])

    @review.user = current_user
    @review.housing = @housing
    if @review.save
      redirect_to housing_path(@housing)
    else
      redirect_to housing_path(@housing), status: :unprocessable_entity
    end
  end


  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/index.html.erb
<h1>books</h1>

<ul>
  <% @books.each do |book| %>
    <li>
      <strong>ID:</strong> <%= book.id %><br>
      <strong>Name:</strong> <%= book.name %>
    </li>
  <% end %>
</ul>

<!-- Asegúrate de incluir las dependencias de datepicker.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" rel="stylesheet">

<script>
  document.addEventListener('DOMContentLoaded', function() {
    $('.datepicker-start').datepicker({
      autoclose: true,
      todayHighlight: true
      // Aquí puedes agregar más opciones de configuración según tus necesidades
    });

    $('.datepicker-end').datepicker({
      autoclose: true,
      todayHighlight: true
      // Aquí puedes agregar más opciones de configuración según tus necesidades
    });
  });
</script>

app/views/housings/_form.html.erb
<div class="container w-50">
<%= simple_form_for(@housing) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, required: true %>
    <%= f.input :price, required: true %>
    <%= f.input :amount_bathrooms, required: true %>
    <%= f.input :amount_rooms, required: true %>
    <%= f.input :msquare, required: true %>
    <%= f.input :city, required: true %>
    <%= f.input :state, required: true %>
    <%= f.input :address, required: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit ,class:'btn btn-primary'%>
  </div>
<% end %>
</div>

app/views/housings/_housing.html.erb
<div id="<%= dom_id housing %>">
  <p>
    <strong>Name:</strong>
    <%= housing.name %>
  </p>

  <p>
    <strong>User:</strong>
    <%= housing.user_id %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= housing.price %>
  </p>

  <p>
    <strong>Amount bathrooms:</strong>
    <%= housing.amount_bathrooms %>
  </p>

  <p>
    <strong>Amount rooms:</strong>
    <%= housing.amount_rooms %>
  </p>

  <p>
    <strong>Msquare:</strong>
    <%= housing.msquare %>
  </p>

  <p>
    <strong>City:</strong>
    <%= housing.city %>
  </p>

  <p>
    <strong>State:</strong>
    <%= housing.state %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= housing.address %>
  </p>

</div>

app/views/housings/edit.html.erb
<h1>Editing housing</h1>

<%= render "form", housing: @housing %>

<br>

<div>
  <%= link_to "Show this housing", @housing %> |
  <%= link_to "Back to housings", housings_path %>
</div>

app/views/housings/index.html.erb
<!-- app/views/bookings/index.html.erb -->
<h1>Listado de reservas</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Fechas</th>
      <th>Cantidad de personas</th>
      <th>Estado</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.id %></td>
        <td><%= booking.start_date %> - <%= booking.end_date %></td>
        <td><%= booking.guest_count %></td>
        <td><%= booking.status %></td>
        <td>
          <%= link_to "Ver", booking_path(booking) %>
          <%= link_to "Editar", edit_booking_path(booking) %>
          <%= link_to "Eliminar", booking_path(booking), method: :delete, data: { confirm: "¿Estás seguro de eliminar esta reserva?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Nueva reserva", new_booking_path %>

app/views/housings/new.html.erb
<h1 class='text-center'>New housing</h1>

<%= render "form", housing: @housing %>

<br>

<div>
  <%= link_to "Back to housings", housings_path %>
</div>

app/views/housings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @housing %>

<div class="">
  <div class="col-12 col-sm-6">
    <div class="bg-white rounded p-3">
      <h5>Add your book</h5>
        <%= simple_form_for [@housing, @book], data: { controller: 'flatpickr' }  do |f| %>
          <%= f.input :start_date, as: :string, input_html: { data: { flatpickr_target: "startTime" } } %>
          <%= f.input :end_date, as: :string, input_html: { data: { flatpickr_target: "endTime" } } %>
          <%= f.submit 'Schedule your appointment' %>
        <% end %>

    </div>
  </div>
</div>

<div class="row">
  <div class="col-12 col-sm-6">
    <h3>Reviews</h3>
    <% if @housing.reviews.empty? %>
      <small><em class="text-muted">Be the first one to review this list</em></small>
    <% end %>
    <% @housing.reviews.each do |review| %>
      <div>
        <% review.rating.times do %>
          <i class="fas fa-star star-yellow"></i>
        <% end %>
        <small><em class="text-muted"><%= distance_of_time_in_words_to_now(review.created_at) %> ago</em></small>
        <p class="mb-0"><%= review.content %></p>
      </div>
      <hr>
    <% end %>
  </div>
  <div class="col-12 col-sm-6">
    <div class="bg-white rounded p-3">
      <h5>Add your review</h5>
      <%= simple_form_for [@housing, @review] do |f| %>
        <%= f.input :content, placeholder: "Add your review here..." %>
        <%= f.input :rating, as: :select, collection: (1..5).to_a, required: true, prompt: "What's your rating", input_html: { data: { controller: "star-rating" } } %>
        <%= f.submit class:"btn btn-flat" %>
      <% end %>
    </div>
  </div>
</div>


<div>
  <%= link_to "Edit this housing", edit_housing_path(@housing) %> |
  <%= link_to "Back to housings", housings_path %>
  <%= button_to "Destroy this housing", @housing, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="row">
  <% @housings.each do |housing| %>
    <div class="col-4 mt-5">
      <%= render "shared/card", housing: housing %>
      <%= link_to housing.name, housing_path(housing) %>
    </div>
  <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/shared/_card.html.erb
<div id="card">
  <%# This div would be the image %>
  <div class="bg-gray w-100" style="width: 150px; height: 150px; background-color: white; border-radius: 12px;"></div>

  <div id="content" class="mt-4" style="display: flex; flex-direction: column; align-items: flex-start;">
    <%# Nombre del housing %>
    <p id="name" style="margin-bottom: 0px; font-weight: 600;"><%= housing.name %></p>

    <%# Nombre de la ciudad %>
    <p id="city" style="margin-bottom: 1px; color: gray;"><%= housing.city %></p>
    <div>
        <i class="fas fa-star star-yellow"></i>
        <small><em class="text-muted"><%= housing.averagee_rating %></em></small>
    </div>
    <%# Fechas disponibles %>
    <p id="availability" style="margin-bottom: 8px; color: gray;">Oct 23 - 28</p>

    <%# Precio por noche %>
    <div id="pricepernight" class='d-flex align-items-end'>
      <h5 style="margin-bottom: 4px;">$<%= housing.price %></h5>
      <p style="margin-bottom: 4px;">/night</p>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_logo.html.erb
<div class="logo">
	<div class="logo__top"></div>
	<div class="logo__sides"></div>
	<div class="logo__loop">
		<span></span>
		<span></span>
		<span></span>
	</div>
	<div class="logo__corners">
		<span></span>
		<span></span>
	</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid py-4 d-flex align-items-center justify-content-between">
    <div>
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag(asset_path('airbnb.png'), style: 'height: 32px; width: auto;') %>
      <% end %>
    </div>

    <div style="box-sizing: border-box; display: flex; flex-direction: row; align-items: center; padding: 8px 8px 8px 24px; gap: 16px; background: #FFFFFF; box-shadow: 0px 2px 4px rgba(31, 41, 55, 0.06), 0px 4px 6px rgba(31, 41, 55, 0.1); border-radius: 1000px; justify-content: space-between; margin: 0 auto; position: relative;">
      <!-- Three options -->
      <select style="border: none;">
        <option value="" disabled selected>Anywhere</option>
        <option value="option1">Santiago</option>
        <option value="option2">Concepción</option>
        <option value="option3">Arica</option>
      </select>

      <div style="border-left: 1px solid #C4C4C4; height: 24px; margin: 0 8px;"></div>

      <select style="border: none;">
        <option value="" disabled selected>Any week</option>
        <option value="option1">This week</option>
        <option value="option2">Next week</option>
        <option value="option3">Next month</option>
      </select>

      <div style="border-left: 1px solid #C4C4C4; height: 24px; margin: 0 8px;"></div>

      <select style="border: none; color: gray;">
        <option value="" disabled selected>Add Guests</option>
        <option value="option1">Placeholder 1</option>
        <option value="option2">Placeholder 2</option>
        <option value="option3">Placeholder 3</option>
      </select>

      <div style="border-left: 1px solid #C4C4C4; height: 24px; margin: 0 8px;"></div>

      <button class="btn btn-primary rounded-pill" style="display: flex; justify-content: center; align-items: center; height: 40px;">
        <svg width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M13.0413 13.0418L9.91634 9.91683M0.958008 6.16683C0.958008 3.29035 3.28986 0.958496 6.16634 0.958496C9.04282 0.958496 11.3747 3.29035 11.3747 6.16683C11.3747 9.04331 9.04282 11.3752 6.16634 11.3752C3.28986 11.3752 0.958008 9.04331 0.958008 6.16683Z" stroke="white" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
      </button>
    </div>

    <% if user_signed_in? %>
      <!-- User dropdown menu -->
      <li class="nav-item dropdown" style="list-style: none;">
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-end rounded-4 mt-2" aria-labelledby="navbarDropdown">
          <%= link_to "Bookings", "#", class: "dropdown-item" %>
          <%= link_to "Your Housing", "#", class: "dropdown-item" %>
          <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
        </div>
      </li>
    <% else %>
      <li class="nav-item dropdown" style="list-style: none;">
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-end rounded-4 mt-2" aria-labelledby="navbarDropdown">
          <%= link_to "Sign In", new_user_session_path, class: "dropdown-item" %>
          <%= link_to "Sign Up", new_user_registration_path, class: "dropdown-item" %>
        </div>
      </li>
    <% end %>
  </div>
</div>